language: php

php:
    - 7.0
    - 7.1
    - 7.2

before-install:
 - composer self-update
 
install:
    - composer install
    
before_script:
 - composer self-update
 - composer install --prefer-source --no-interaction --dev
 
 script: phpunit

notifications:
    email:
        - igor@route4me.com
        - oleg@route4me
